import type { ReactNode } from "react";
import { ArrowLeftRight, Edit3, Trash2 } from "lucide-react";
import { EmptyState } from "@/shared/components/EmptyState";
import { formatDateTime } from "@/shared/utils/formatters";
import type { InventoryMaterial, StockMove, StockMoveType } from "../types/inventory";

const moveLabels: Record<StockMoveType, string> = { ENTRADA: "Entrada", SALIDA: "Salida", AJUSTE: "Ajuste" };

export function InventoryMaterialsTable({ materials, onEdit, onMove, onDelete, canEdit, canMove, canDelete }: { materials: InventoryMaterial[]; onEdit: (material: InventoryMaterial) => void; onMove: (material: InventoryMaterial) => void; onDelete: (material: InventoryMaterial) => void; canEdit: boolean; canMove: boolean; canDelete: boolean; }) {
  if (materials.length === 0) return <EmptyState title="No hay materiales para mostrar" description="Crea el primer material o ajusta los filtros de búsqueda." />;
  const hasActions = canEdit || canMove || canDelete;
  return <div className="overflow-x-auto"><table className="w-full min-w-200 text-left"><thead className="border-y border-gray-100 text-xs text-text-muted"><tr><th className="py-3 font-medium">Material</th><th className="py-3 font-medium">Categoría</th><th className="py-3 font-medium">Existencia</th><th className="py-3 font-medium">Mínimo</th><th className="py-3 font-medium">Estado</th>{hasActions ? <th className="py-3 text-right font-medium">Acciones</th> : null}</tr></thead><tbody className="divide-y divide-gray-100">{materials.map((material) => <tr key={material.id} className="text-sm"><td className="py-4 pr-5"><p className="font-medium text-text-primary">{material.name}</p>{material.description ? <p className="mt-0.5 max-w-xs truncate text-xs text-text-muted">{material.description}</p> : null}</td><td className="py-4 text-text-secondary">{material.category.name}</td><td className="py-4 font-medium text-text-primary">{material.stock} <span className="font-normal text-text-muted">{material.unit.name}</span></td><td className="py-4 text-text-secondary">{material.minimumStock} {material.unit.name}</td><td className="py-4"><InventoryStockState material={material} /></td>{hasActions ? <td className="py-4"><div className="flex justify-end gap-1">{canMove ? <ActionButton label="Registrar movimiento" onClick={() => onMove(material)}><ArrowLeftRight className="h-4 w-4" /></ActionButton> : null}{canEdit ? <ActionButton label="Editar material" onClick={() => onEdit(material)}><Edit3 className="h-4 w-4" /></ActionButton> : null}{canDelete ? <ActionButton label="Eliminar material" danger onClick={() => onDelete(material)}><Trash2 className="h-4 w-4" /></ActionButton> : null}</div></td> : null}</tr>)}</tbody></table></div>;
}

export function InventoryMovesTable({ moves }: { moves: StockMove[] }) { if (moves.length === 0) return <EmptyState title="Sin movimientos registrados" description="Los ingresos, salidas y ajustes aparecerán aquí." />; return <div className="divide-y divide-gray-100 border-y border-gray-100">{moves.map((move) => <InventoryMoveRow key={move.id} move={move} />)}</div>; }

export function InventoryMoveRow({ move, compact = false }: { move: StockMove; compact?: boolean }) { const signedQuantity = `${move.quantity > 0 ? "+" : ""}${move.quantity}`; return <div className={`grid gap-2 py-3 text-sm ${compact ? "grid-cols-[1fr_auto]" : "sm:grid-cols-[1.4fr_0.7fr_0.7fr_1fr_auto] sm:items-center"}`}><div><p className="font-medium text-text-primary">{move.material.name}</p><p className="mt-0.5 text-xs text-text-muted">{formatDateTime(move.date)}</p></div><span className="text-text-secondary">{moveLabels[move.type]}</span><span className={move.quantity < 0 ? "font-medium text-danger" : "font-medium text-success"}>{signedQuantity} {move.material.unit?.name ?? ""}</span>{!compact && <span className="truncate text-text-secondary">{move.description || "Sin referencia"}</span>}{!compact && <span className="text-xs text-text-muted">{move.user?.name ?? "Sistema"}</span>}</div>; }

export function InventoryStockState({ material }: { material: InventoryMaterial }) { if (material.stock === 0) return <span className="text-xs font-medium text-danger">Sin existencias</span>; if (material.minimumStock > 0 && material.stock <= material.minimumStock) return <span className="text-xs font-medium text-warning">Bajo mínimo</span>; return <span className="text-xs font-medium text-success">Disponible</span>; }
function ActionButton({ label, onClick, children, danger = false }: { label: string; onClick: () => void; children: ReactNode; danger?: boolean }) { return <button type="button" aria-label={label} title={label} onClick={onClick} className={`rounded p-2 transition-colors ${danger ? "text-text-muted hover:bg-red-50 hover:text-danger" : "text-text-muted hover:bg-gray-100 hover:text-text-primary"}`}>{children}</button>; }
