export const EquipmentKeys = {
  all: ["equipments"] as const,
  lists: () => [...EquipmentKeys.all, "list"] as const,
  list: (params?: any) => [...EquipmentKeys.lists(), params] as const,
  details: () => [...EquipmentKeys.all, "detail"] as const,
  detail: (id: string) => [...EquipmentKeys.details(), id] as const,
  models: () => [...EquipmentKeys.all, "models"] as const,
  model: (id: string) => [...EquipmentKeys.models(), id] as const,
  sites: () => [...EquipmentKeys.all, "sites"] as const,
  assignment: (id: number) => [...EquipmentKeys.all, "assignment", id] as const,
  locationHistory: (id: string) => [...EquipmentKeys.all, "location-history", id] as const,
  customerDocumentStatus: (id: string) => [...EquipmentKeys.all, "customer-document-status", id] as const,
  customerDocuments: (id: string) => [...EquipmentKeys.all, "customer-documents", id] as const,
  customerAssignmentDocuments: (id: string) => [...EquipmentKeys.all, "customer-assignment-documents", id] as const,
  labelPrints: (id: string) => [...EquipmentKeys.all, "label-prints", id] as const,
  dashboard: () => [...EquipmentKeys.all, "dashboard"] as const,
  assignments: (params?: unknown) => [...EquipmentKeys.all, "assignments", params] as const,
  inactivityAlerts: (params?: unknown) => [...EquipmentKeys.all, "inactivity-alerts", params] as const,
  monitoringSettings: () => [...EquipmentKeys.all, "monitoring-settings"] as const,
  modelMonitoringProducts: (id: number) => [...EquipmentKeys.all, "model-monitoring-products", id] as const,
};
